### ISSUE TITLE
Checklist for CRAN submission

### ISSUE THREAD

**Issue by thomasp85** [thomasp85/lime#22]
- [x] Settle on return format
- [x] Decide on image inclusion
- [x] Remove unwanted dependencies
- [x] Improve unit tests
- [x] Improve `plot_text_explanation`
- [x] Vignette
- [x] Logo

**Comment by thomasp85** [comment]
@pommedeterresautee you are much welcome to comment and add to the list.

I think personally that we should focus on cleaning up the current features and get it on CRAN, waiting with image analysis for a later release - first and foremost because it will be nice to get on CRAN and get some people to use it, and because I think image predictions are quite niche in R (I might be wrong)

**Comment by pommedeterresautee** [comment]
I share your opinion regarding image processing (but may change with MxNet...)
Anyway, better to release on Cran.
I will work on the cleaning, etc. at the end of the week

**Comment by pommedeterresautee** [comment]
For unit test, can you setup covr? It makes easy to see if we are massively missing a part of the program.

Regarding return format, for DF, the result of the preprocessing is a just model, like any other learning algo (it is learning boundaries of the bins) . If we have this understanding, the result of the "preprocessing" which is in fact a learning should be managed like any other model in R as an object created by a function and provided to the `explainer` function through a parameter (here explainer function has the role of predict function).

That approach would fix both the return type, because returning a function is unusual in R world and may be hard to understand for first time users who don't RTFM, and avoid having the `x` parameter in `lime.character` which has no purpose). 

Does it make sense? Is there something I am not seeing regarding the DF part? (I have not really used it outside of some tests so I may miss something)

**Comment by pommedeterresautee** [comment]
When you merge I remove maggritr and purrr dependencies

**Comment by thomasp85** [comment]
Have you had a look at the new PR? `lime` is no longer returning a function...

**Comment by pommedeterresautee** [comment]
Sorry I opened the master branch file and thought this was the new one... my bad.

**Comment by pommedeterresautee** [comment]
So this is now managed as a model :-)

**Comment by thomasp85** [comment]
jep - I also thought we were aligned but just wanted to be sure

**Comment by thomasp85** [comment]
I'll merge the PR - and we can take it from there

**Comment by pommedeterresautee** [comment]
What is the purpose of the x in lime.character?
It is included in envirnment then you erase it, true ?

**Comment by pommedeterresautee** [comment]
I am thinking now we have really two parts, lime.character is not really needed, don't you think? We can put everything in explainer.character

**Comment by thomasp85** [comment]
It ensures the correct dispatch along with consistent API...

`lime` is a one-off call where the return value is saved along with the model, while `explain` is meant to be called again and again with new input.

**Comment by thomasp85** [comment]
We could - we are again touching upon the tension between consistent API and removal of boilerplate code. As before we stand on opposite sites here:-)

**Comment by thomasp85** [comment]
I strongly believe it will confuse users to have different APIs for this - they don't need to know whether training the explainer for text predictors is a zero-operation, just that in the `lime` package you train an explainer and then use it to explain new predictions...

**Comment by pommedeterresautee** [comment]
Haha I know, classic positions now :-) There is still a diff with before, with the PR, the first part does absolutely nothing now in lime.character, there no more logic. And is it that inconsistent? I mean in previous discussions I was advocating for a complete independant API dedicated to the task, here I am just asking to remove a call to a function. But the explain part, which is the main part is the same. So we can easily say the API are consistents.

I wanted to make the point, but FYI I don t care that much now that the returned function is gone :-)

**Comment by thomasp85** [comment]
:-)

Well, since I care we are keeping it...

**Comment by thomasp85** [comment]
It's merged - you are free to remove `purrr` and `magrittr`

**Comment by thomasp85** [comment]
2 down - 3 to go

Will you look at improving the text plotting as we discussed? Then I'll have fun with the unit tests:-)

**Comment by pommedeterresautee** [comment]
Return format is settled, isn't it?
So 3/2 :-)
Regarding the plot, I don t know if I will have time today... will do my best
Regarding unit test, really `covr` is useful, in particular at the begining, just to have an idea what is missing, but I don't really believe in the close to 100% goal)

**Comment by thomasp85** [comment]
Yeah - I'm using `covr` in all my packages in general so no need to convince me. Don't feel pressure to do it today...

Not aiming for 100% in any way - that's usually a futile goal. We just need to cover the most central functionality...

**Comment by thomasp85** [comment]
I would also like to avoid using caret in the examples. The way it handles dependencies means that it is necessary to add a lot of Suggests to `lime` directly. I'll try to write it out...

**Comment by thomasp85** [comment]
We might want to write a short vignette describing the theory of `lime` (I think many shy away from reading an academic article) and how to interpret the results...

**Comment by pommedeterresautee** [comment]
Remove unwanted dependencies -> dplyr and tibble are still in Imports, e1071 and MASS are in suggest

**Comment by thomasp85** [comment]
Yep - working on that right now

**Comment by thomasp85** [comment]
@pommedeterresautee I've tried to replicate your polling of text into one explanation from earlier versions in the latest commit - can you have a look?

**Comment by thomasp85** [comment]
Removed all extraneous dependencies - MASS stays to support examples but as it is part of default R installation it shouldn't be a pain point

**Comment by pommedeterresautee** [comment]
@thomasp85 sure, but will do it next week if this is Ok for you.

**Comment by thomasp85** [comment]
Sure, no rush

**Comment by thomasp85** [comment]
I've made a vignette - can you have a look? If you feel for it you are very welcome to add a text explanation example...

**Comment by pommedeterresautee** [comment]
About the Vignette, if I add my text, it will be a super long vignette, why not make 3 (just divides the existing one in general and applied to DF, and I add text)?
In any case, I will write something, so you can uncheck Vignette in the ToDo.
Text explanation plot is now finished (last PR). Let me know what you think. With Shiny, it seemed to me I need something below instead that on the side as I thought first.

**Comment by thomasp85** [comment]
Do you have any idea whether it will be possible to make it interactive with pure JS, thus removing shiny dependency (I know it is possible, rather, is it feasible?).

Removing shiny will make it easier to include it in html reports...

**Comment by pommedeterresautee** [comment]
My knowledge in Js is quite low, no idea of how hard it would be.
But I would be happy to remove shiny too if this is possible.

**Comment by thomasp85** [comment]
I agree we should keep shiny for now. Beginning to write it out will side track the CRAN release. When time permits I might look into porting it to js - shouldn't be too problematic

**Comment by thomasp85** [comment]
If you just write a vignette for text I think we will be fine - I'll keep the tabular data together with the main vignette as it is quite short...

**Comment by pommedeterresautee** [comment]
There is also a note on Windows:
```
* checking compiled code ... NOTE
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
File 'lime/libs/i386/lime.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'
It is good practice to register native routines and to disable symbol
search.
See 'Writing portable packages' in the 'Writing R Extensions' manual.
* checking examples ... OK
Examples with CPU or elapsed time > 5s
      user system elapsed
```

I have the same on another package.
This was supposed to fix it:
http://thecoatlessprofessor.com/programming/r/registration-of-entry-points-in-compiled-code-loaded-into-r/
But `tools::package_native_routine_registration_skeleton(".")` do nothing :(

**Comment by thomasp85** [comment]
Are you on an updated R with the latest Rcpp version? Native routine registration is done automatically by Rcpp, but may get overridden locally when you build (see the bottom of the RcppExports.cpp file in this repo and compare with your local one)

**Comment by pommedeterresautee** [comment]
I am on 3.4.1
I know about https://github.com/RcppCore/Rcpp/pull/694 but still... there is the note on Windows.

**Comment by thomasp85** [comment]
Do you get this locally as well or is it from the appveyor check?

**Comment by thomasp85** [comment]
I'll take care of this somehow - just focus on the vignette and we'll soon be ready to ship

**Comment by thomasp85** [comment]
Is it possible (easy) to add text wrapping in the output of `plot_text_explanations`? It doesn't look nice inside a RMarkdown HTML document...

**Comment by thomasp85** [comment]
@pommedeterresautee can I get you to try and update RTools for your windows R installation and see if the note persists?

**Comment by pommedeterresautee** [comment]
For RTools I had to reinstall the 3.3 for some reasons few weeks ago. I left the office, no more access to Windows, will try tomorrow... Have you thought to post the issue on lists.r-forge.r-project.org/pipermail/rcpp-devel/ ? Warning: Dirk can be very.... R Core spirit :-)

**Comment by thomasp85** [comment]
Dirk is fine, if a little heated sometimes. I got word from Jim Hester that it is related to the tool chain and not to anything in the package itself so we should check that first

**Comment by pommedeterresautee** [comment]
Will try the not freeze version 3.4 tomorrow.

**Comment by thomasp85** [comment]
Good work on the `plot_text_explanations`! I'll make a logo tomorrow and once you have confirmed (hopefully) that the windows note has nothing to do with lime I'll submit.

**Comment by thomasp85** [comment]
Getting pretty close :-) how are you on the windows side?

**Comment by thomasp85** [comment]
Going to test up against the r-hub build machines which should mimic those of CRAN, so if it passes there I will submit...

**Comment by pommedeterresautee** [comment]
'''
checking compiled code ... NOTE
File 'lime/libs/x64/lime.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'

It is good practice to register native routines and to disable symbol
search.

See 'Writing portable packages' in the 'Writing R Extensions' manual.
'''

**Comment by pommedeterresautee** [comment]
```
> devtools::session_info()
Session info ------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.359)           
 language (EN)                        
 collate  French_France.1252          
 tz       Europe/Paris                
 date     2017-09-14                  

Packages ----------------------------------------------------
 package   * version date       source        
 base      * 3.4.1   2017-06-30 local         
 compiler    3.4.1   2017-06-30 local         
 datasets  * 3.4.1   2017-06-30 local         
 devtools    1.13.3  2017-08-02 CRAN (R 3.4.1)
 digest      0.6.12  2017-01-27 CRAN (R 3.4.0)
 graphics  * 3.4.1   2017-06-30 local         
 grDevices * 3.4.1   2017-06-30 local         
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.0)
 methods   * 3.4.1   2017-06-30 local         
 stats     * 3.4.1   2017-06-30 local         
 tools       3.4.1   2017-06-30 local         
 utils     * 3.4.1   2017-06-30 local         
 withr       2.0.0   2017-07-28 CRAN (R 3.4.1)
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.0)
```

**Comment by thomasp85** [comment]
Strange... Is this with the latest installation of Rtools? Anyway, lets see what CRAN says

**Comment by pommedeterresautee** [comment]
Yes, RTools 3.4 just reinstalled today, and yes, let s see Cran answer.
